image: node:16

variables:
  REDIS_URL: redis://localhost:6379
  REDIS_CHANNEL: broadcasthub
  AUTH_TIMEOUT: 5000
  WS_PORT: 80
  ENABLE_MULTITENANCY_MODE: 'false'
  TINE20_JSON_API_URL: http://localhost:4000
  # Pattern gets anchored in the code
  TINE20_JSON_API_URL_PATTERN: (http://localhost:4000)|(http://tenant(1|2|3).my-domain.test:4000)
  DEBUG_DEFAULT_LOGGING: "off"
  DEBUG_LOG_TO_FILE: "off"
  DEBUG_LOG_FILE: ../../stdout.log
  TEST_INTEGRATION_WS_URL: ws://localhost:80
  TEST_E2E_WS_URL: ws://localhost:80

cache:
  paths:
  - node_modules/

all_tests:
  script:
   - npm install
   - npm run-script integrationtest
