image: node:14

variables:
  REDIS_URL: redis://localhost:6379
  REDIS_CHANNEL: broadcasthub
  WS_PORT: 80
  TINE20_JSON_API_URL: http://localhost:4000/index.php?requestType=JSON
  TINE20_BROADCAST_CHANNEL: broadcasthub
  DEBUG_DEFAULT_LOGGING: "off"
  DEBUG_LOG_TO_FILE: "off"
  DEBUG_LOG_FILE: ../../stdout.log
  TEST_INTEGRATION_WS_URL: ws://localhost:80
  TEST_E2E_WS_URL: ws://localhost:80

cache:
  paths:
  - node_modules/

all_tests:
  script:
   - npm install
   - npm run-script integrationtest
