version: '3'
services:
    redis:
        image: redis:5-alpine
        ports:
            # conflict with other project
            #- 6379:6379
            - 7379:6379
        volumes:
            - ./config/redis.conf:/usr/local/etc/redis/redis.conf
        command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
